apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5555 # Sets port to run the postgres application
      targetPort: 5432
  selector:
    app: postgres

# kubectl apply -f postgres-service.yaml 